---
title: "Augustin_Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#IMPORT THE DATA

getwd()
setwd("/Users/Augustin/Documents/GitHub/DSBA-Group10/WD")

area_data <- read.csv("Community_Statistical_Areas__CSAs___Reference_Boundaries.csv")

cctv_data <- read.csv("Baltimore_CCTV_Locations_Crime_Cameras.csv")

poverty_data <- read.csv("Percent_of_Family_Households_Living_Below_the_Poverty_Line.csv")

crime_data <- read.csv("Baltimore_Part1_Crime_data.csv")

#EXPLORE THE DATA

#Crime data
View(crime_data)
str(crime_data)
summary(crime_data)
unique(crime_data$Neighborhood)
tolower(crime_data$Neighborhood)

#Area data
View(area_data)

#Poverty data
View(poverty_data)

#CCTV data
View(cctv_data)


#DATA MANIPULATIONS

library(tidyverse)
library(data.table)
library(sp)
library(rgdal)
library(ggplot2)

#Joining of crime dataset and area dataset

crime_data <- mutate(crime_data,neighborhood=tolower(crime_data$Neighborhood)) #Creation of new column with lower case letters

area_data2 <- separate_rows(area_data, Neigh, sep = ", ") #Creation of a new dataset with eigh neighbourhood being assigned to an area

area_data2 <- mutate(area_data2,neigh=tolower(Neigh)) #Creation of new column with lower case letters

colnames(crime_data)[20] <- "neigh" #Change name to ensure it corresponds to the name we have in other dataset

crime_data_with_areas <- crime_data %>% 
  left_join(area_data2,by="neigh") 

testNA <- is.na(crime_data_with_areas$neigh) #Check whether we have NAs

which(is.na(crime_data_with_areas$neigh))
testNA2 <- rep(FALSE,350294)

identical(testNA,testNA2) #It seems that we have a perfect match !!!

#Calculation of the crime rate per community

CrimeRatePerArea <- crime_data_with_areas %>% 
  group_by(Community) %>%
  summarize(CrimeRatePerArea=(n()/350294)*100)
  
sum(CrimeRatePerArea$CrimeRatePerArea) #The total sum is 100, which is what we expect

#Calculation of the density of CCTV per community

#read in data table
balt_dat <-  fread("Baltimore_CCTV_Locations_Crime_Cameras.csv")

#convert to data table
balt_dat <- as.data.table(balt_dat)

#make data spatial
coordinates(balt_dat) <-  c("X","Y")
crs.geo1 <-  CRS("+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs +type=crs")
proj4string(balt_dat) <-  crs.geo1  

plot(balt_dat, pch = 20, col = "steelblue")

#read in shapefile of baltimore
baltimore <-  readOGR(dsn = "./Community_Statistical_Area", layer = "Community_Statistical_Area") #name of file and object
proj4string(baltimore) <- crs.geo1

#plot
plot(baltimore,main="Spread of CCTVs in different communities of Baltimore")
plot(balt_dat,pch=20, col="steelblue" , add=TRUE)

#Perform the count

proj4string(balt_dat)
proj4string(baltimore)

res2 <- over(balt_dat,baltimore)
counts <- table(res2$community)
counts <- as.data.frame(counts)
colnames(counts)[1] <- "Community"
sum(counts$Freq)

#Calculate the density for each community

CCTV_per_area <- area_data[2] %>% 
  left_join(counts,by="Community") #One must add the communities where there are no counts i.e no CCTV

CCTV_per_area[is.na(CCTV_per_area)] <- 0

CCTV_per_area <- mutate(CCTV_per_area, density_perc=(CCTV_per_area$Freq/(sum(CCTV_per_area$Freq)))*100)

View(CCTV_per_area)

#EXPLORATION

#CCTV against crimes

CCTV_VS_crimes <- CCTV_per_area %>% 
  left_join(CrimeRatePerArea,by="Community")
  
View(CCTV_VS_crimes)

plot(CCTV_VS_crimes$CrimeRatePerArea,CCTV_VS_crimes$density_perc, main="Crime Rate per Community VS CCTV Density per Community",xlab="CrimeRatePerCommunity",ylab="CCTVDensityPerCommunity")

regression <- lm(CCTV_VS_crimes$density_perc~CCTV_VS_crimes$CrimeRatePerArea)
summary(regression)

y<-regression[["coefficients"]][["(Intercept)"]]
x<-regression[["coefficients"]][["CCTV_VS_crimes$CrimeRatePerArea"]]

plot(regression)

range <- seq(from=0, to=4.5, by=0.1)

estimation <- x*range+y

lines(range,estimation, col="blue")

#MAPPING OF CRIMES

baltimore$community %in% CrimeRatePerArea$Community

CrimeRatePerArea$Community[56] <- "Unassigned -- Jail" #The previous line of code allowed to check whether we had a perfect match, so it is not the case, we assign a new value to the only outlier

baltimore@data <- left_join(baltimore@data, CrimeRatePerArea, by = c('community' = 'Community'))

library(tmap)
qtm(baltimore, "CrimeRatePerArea")

#MAPPING OF CCTVs

baltimore$community %in% CCTV_per_area$Community

baltimore@data <- left_join(baltimore@data, CCTV_per_area, by = c('community' = 'Community'))

qtm(baltimore, "density_perc",fill.title="CCTV Density", fill.style="fixed", fill.breaks=c(0,1,2,3,4,5,6,7,8,9,10,11))


#STATISTICS OF CRIME BY TYPES OF CRIME


#RESEARCH QUESTION 
