# Conclusion {.tabset}

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source(here::here("scripts/setup.R"))
```

### 5.1 Summary of our results

<br><br>

Our efforts to analyse the data obtained on Baltimore's open data portal have enabled us to not only observe some interesting phenomena but also to relate them and draw conclusions. 
<br><br>
First, we were able to observe the distribution of surveillance cameras in Baltimore City and found that they were mostly concentrated in the city centre. We also found that crime per capita was highest in the inner city, suggesting a correlation between crime and CCTV. Analysing crime by type, we found some slight differences by communities: communities on the east side of the city seem to be slightly more affected by less severe crime and property crime, while communities on the west side of Baltimore seem to be more affected by more severe crime and violent crime.  Moreover, despite low statistical significance, it seems to have been detected that poorer areas tend to be more affected by crime in general. After this rather spatial analysis of crime, a temporal analysis revealed that over the period 2014-2019, crime (in absolute numbers) had increased slightly, although there has been a downward trend since a peak in 2017. We also observed that crime was seasonal in Baltimore and that crime tended to decline in winter. Finally, we found that over the 2014-2019 period, felonies increased as did violent crime, while misdemeanours and property crime decreased. This suggests that more violent and severe crimes have increased while less severe and property crimes have decreased. 
<br><br>
These exploratory analyses provided the basis for answering our several research questions. We first investigated whether CCTVs were effective in deterring crime by looking at the relationship between crime evolution and CCTV density. This analysis showed that there did not appear to be a significant relationship between these two variables. By comparing the evolution of crime in areas with a high CCTV density with areas with a low CCTV density, we were not able to demonstrate a trend. A more spatial analysis of the phenomenon allowed us to confirm this conclusion by showing that a lot of crime was committed, sometimes right in front of the surveillance cameras. We used the same methodology to investigate whether surveillance cameras could have a specific impact on certain types of crime. We were unable to find a significant correlation between the evolution of any of the four types of crime observed and CCTV density, suggesting that CCTV cameras were not particularly effective for a certain type of crime either. However, one of the findings of this analysis was that there is a particularly strong correlation between CCTV density and violent crime per capita. The failure to demonstrate the effectiveness of CCTVs on crime made it impossible to answer our third research question. However, we wanted to examine how crime evolved by areas according to its level of poverty in order to see if we could detect inequalities in terms of the 'right to safety'. Our regression results indicate that there is no correlation between changes in crime and poverty level. Finally, we tried to analyse what could determine the CCTV density of an area Indeed, as mentioned in the introduction, human rights activists are concerned that  most disadvantaged people do not enjoy the same privacy as the rest of the population. We found that there indeed is a correlation between poverty level and CCTV density. However, the relationship is  weak. Always in the aim of finding out what determines the CCTV density of a given area, we performed a stepwise regression containing plenty of different variables. We arrived to the conclusion that the most important determinant of CCTV density was not race, nor education of socio-economic condition but rather violent crime per capita. This result is somehow reassuring, although we have just highlighted that CCTVs were not particularly effective in deterring violent crime.

### 5.2 Take home message

<br><br>

Some of the fears of leading civil rights advocates seem to be justified, others less so. Indeed, given that the effectiveness of surveillance cameras is difficult to demonstrate and that the gain in security generated by them is consequently limited in relation to the loss of privacy they cause, the principle of proportionality does not seem to be respected. It might be that CCTVs actually lead to more restrictions of citizens' freedom than they increase their security. It is therefore legitimate to doubt the validity of massive data collection under the guise of protecting the population. Even people who have "nothing to hide" and therefore don't mind losing some of their privacy because they think they are "safer" with the camera would be well advised to reconsider their views. However, with regard to the civil rights advocates' fears that the government systematically and specifically targets certain members of the population who are already disadvantaged, it is impossible for us to confirm this with the data available to us. 
<br><br>
Based on the results of our analysis, we believe that it would be essential for the Baltimore Police Department to offer transparency to their citizens. Indeed, we believe that the latter would be legitimate to demand the following from their authorities :

  + a report demonstrating that surveillance cameras and the massive collection of its citizen's data can still have positive effects. Indeed, it is possible that although surveillance cameras are not effective in deterring crime, they could potentially have other positive effects such as facilitating the arrest of criminals. Yet, it would be necessary to verify such potential effects.

  + a detailed report explaining the criteria on which the government bases its decision to implement a surveillance camera

### 5.3 Limitations

<br><br>

Obviously, our work has its limitations. The main one is the limited number of surveillance cameras in our original data set. As mentioned in section 2.2, one of the columns of our data set is called "CAM_NUM", not having all the camera numbers contained in our data set, it seems to suggest that only a fraction of the surveillance cameras installed in Baltimore are mentioned in the data set. This would make sense that the Baltimore Police Department does nto discolse publicly the exact location of **all** its CCTVs. Furthermore, based on our common sense, it does seem that 836 cameras is a bit too few for a city the size of Baltimore. Some communities do not even have CCTVs according to the data set. This is problematic because it limits the significance of our regressions for example. It is also worth mentioning that the fact that we ran our regressions with only 56 values at a time makes it difficult to get very significant results and makes our conclusions more fragile. A higher number of observations would have been desirable. 

Another limitation is the lack of information on when the surveillance cameras were installed. Indeed, this would have allowed us to more accurately assess the effectiveness of CCTVs but also to answer a question we would have liked to answer, namely: can CCTVs generate crime displacement issues? 

Finally, it is also important to mention that while answering our fourth research question, using violent crime per capita as the sole independent variable, we were only able to explain 50% of the variance of the CCTV density of an area. While this result is encouraging, it still means that there is another half of the variance that we cannot explain with the data we have. It is therefore possible that the government is indeed systematically targeting a section of the population and that we simply have not found the criteria on which they are doing this. Indeed, the spread of surveillance cameras in Baltimore does not seem to be random as one can discern certain patterns (e.g. certain areas are particularly populated with cameras, certain cameras seem to be aligned on certain streets etc...).
<br>

### 5.4 Future work 

<br><br>

We think that it would be interesting to carry out the same analyses as we did with a data set comprising all of the city's surveillance cameras in order to check whether similar conclusions are obtained. Also, access to more information would allow us, for example, to invalidate or not the hypothesis that surveillance cameras could displace crime. 
<br><br>
Secondly, it would be of particular interest to do similar analyses with other cities and to analyse whether it is possible to create a model capable of 'predicting' CCTV density as a function of crime levels. Indeed, one could build a model on our Baltimore data set and treat it as test set, and then apply this model on another data set of a different city.
<br><br>
Finally, we believe that it would be very important to analyse the impact that alternative and less privacy-threatening measures to deter crime could have. For example, prevention campaigns aimed at nudging people in doing good through showing some poster with some motivational verses - i.e. "Do to others how you yourself want to be treated", the establishment of youth centers aimed at preventing juvenile crime and gang enrollment, or the establishment of "neighbourhood watch" crime prevention programmes.

### 5.5 References 

ACLU. (2021, February 21). *Ten years after first warning, Chicago's massive surveillance camera system continues to pose an unregulated threat to privacy*. Retrieved October 06, 2021, from ACLU: https://www.aclu-il.org/en/news/ten-years-after-first-warning-chicagos-massive-surveillance-camera-system-continues-pose

Gellman, B., & Adler-Bell, S. (2017, December 21). *The Disparate Impact of Surveillance*. Retrieved October 06, 2021, from TCF: https://tcf.org/content/report/disparate-impact-surveillance/

Madden, M., & Rainie, L. (2015, May 20). *Americans’ Attitudes About Privacy, Security and Surveillance*. Retrieved October 06, 2021, from Pew Research Center: https://www.pewresearch.org/internet/2015/05/20/americans-attitudes-about-privacy-security-and-surveillance/

Ossola, A. (2019, April 11). *Cameras are everywhere. Do they make us any safer?* Retrieved October 05, 2021, from QZ: https://qz.com/1589864/do-cameras-and-drones-everywhere-make-us-any-safer/

Waples, S. G. (2009). Does CCTV displace crime? *Criminology & Criminal Justice*, 9(2), 207–224.



