# Executive summary {.tabset}

### Overview and motivation

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source(here::here("scripts/setup.R"))
```

## Research goal 

How do governments decide where and how to install CCTVs? The goals of this project is an investigation of i) finding the root causes and criteria which -backed up by data - determine CCTV installment in Baltimore, ii) the crime deterrent potential of CCTVs in the Amercian city of Balimore and iii) the impact on the communities themselves. 

## Methodology

Using six datasets, we found and combined relevant data about crimes committed in Baltimore, CCTV locations in the city, poverty rates, the are of Baltimore, the population and the households with internet access.

## Main Takeaways

First, our analysis shows quite well that CCTV placement seems to follow areas where crime per capita is highest. Looking at the North-western and South-western areas of Baltimore, it can be seen that the placement of CCTVs aligns rather well with the areas considered dangerous.

Second, CCTCs capture activities within 256ft (~2 blocks). Nevertheless, we see that some crimes are committed directly in front of CCTVs. Although this is not conclusive evidence, this observation goes against the idea that CCTVs are effective crime deterrents. MOreover, for August 2021 the crime rate per area was highest in the Downtown area.  Looking deeply into the Downtown area, we quite clearly see that some crimes are committed right next to some CCTVs. 

Third, regarding crime types our analysis and results of a simple linear regression show a weak $R^2$ for both felonies and misdemeanors. It therefore does not seem like the presence of CCTV has a particularly strong impact on a certain type of crime. 

Fourth, regarding wealth and CCTVs our data shows a poor $adjusted R^2$ and correlation between CCTV density and wealth. One of our initial hypothesis was that the government respected more the privacy of wealthier people, which turned out to be proven wrongly by data. However, we are not sure whether wealth is the only influential factor. Again, in the northern parts we see less CCTV, less crime, and also a more wealthier population.

Fifth, regarding the distribution and pattern of crime types in Baltimore. The idea here is to analyse whetherwe tend to observe an equal distribution of felony and misdemeanors in each area with one outlier: In Downtown, misdemeanor per capita is much larger than the felony per capita and it must be mentioned that this area also is one of the richest area in Baltimore. This suggests that richer areas are more impacted by less severe crimes.


## Conclusion

Overall, we see much more through our multiple regression that the main determining and significant variable influencing the CCTV placement decisions of the government officials are the felonies committed in a community. Thus, we can trust that unfair considerations such as the wealth level of the neighborhoods, the race or educational level. In that way, the trust against government shoud and can be reduced in Baltimore. 